# Class 2b: Numpy

First the library

In [1]:
#Import library
import numpy as np

In [2]:
# Create a Numpy array

a = np.array([1,2,3,4,5.0])
print(a)

[1. 2. 3. 4. 5.]


In [3]:
#Print each element of array a

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 1.0
a[1]: 2.0
a[2]: 3.0
a[3]: 4.0
a[4]: 5.0


In [4]:
# What is the type?
type(a)

numpy.ndarray

- Numpy arrays always store data using the same system.
- If the array has for example only one floating point, then it will transform all integers to floats.
- We can see the type of data stored using the command ARRAY_NAME.dtype
- We can also change the values ​​of an array in the same way as with a list.

In [5]:
c = np.array([20,1,3,4,5])
c

array([20,  1,  3,  4,  5])

In [6]:
# change the first element
c[0]=100
c

array([100,   1,   3,   4,   5])

In [7]:
#To change the last element we need to use the length of the array -1

c[4] = 8
c

array([100,   1,   3,   4,   8])

We can cut the arrays (slicing)

In [10]:
# Lets take out the first and last elements
d = c[1:4]
d

array([1, 3, 4])

In [11]:
# we can also change multiple elements
c[3:5] = 300, 400
c

array([100,   1,   3, 300, 400])

## Assign values by list

In [12]:
#create a list

seleccion = [0,2,3]

In [14]:
#Since c is already an array, now we can select elements it via the list
d = c[seleccion]
d

array([100,   3, 300])

In [15]:
# Or change elements via the list
c[seleccion] = 42
c

array([ 42,   1,  42,  42, 400])

In [16]:
# Lets create a new array
a = np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#Checking size with python len(x) vs numpy x.size
print(len(a))
print(a.size)

10
10


In [19]:
# Arrays can be single points, vectors, matrcies... Lets check the dimensions

a.ndim

1

In [20]:
#and the shape...

a.shape

(10,)

### So what is so cool about numpy?

In [21]:
# Get the mean? easy
promedio = a.mean()
promedio

4.5

In [22]:
#Standard deviation? easy
desviacion_estandar = a.std()
desviacion_estandar

2.8722813232690143

In [23]:
#How about highest value? easy

max_a = a.max()
max_a

9

In [24]:
# of course the minimum too
min_a = a.min()
min_a

0

### Operations?

In [25]:
#Vector addition
u = np.array([1,0])
v = np.array([0,1])
v+u

array([1, 1])

In [26]:
#Multiplication
y = np.array([1,2])
z=2*y
z

array([2, 4])

In [28]:
# 1 to 1 multiplication
w = np.array([3,2])
print('w:',w)
print('y:',y)
j=y*w
print('w*y:', j)

w: [3 2]
y: [1 2]
w*y: [3 4]


In [29]:
#dot product
np.dot(w,y)

7

In [30]:
#add a constant
u = np.array([1,2,3,-1])
u+1


array([2, 3, 4, 0])

In [34]:
# El valor de pi...

np.pi

x= np.array([0, np.pi/2, np.pi])

y = np.sin(x)
y

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

###  What about big arrays?

Linspace is a function to generate numbers spaced by a chosen interval.

In [32]:
# lets make a array with 9 elements that spans [-2:2]

np.linspace(-2, 2, num=9)

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ])

In [33]:
# very usefull to creat an x-axis on which to throw a function

x = np.linspace(0,2*np.pi, 10)
x

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

In [35]:
# the sin of x is
y =np.sin(x)
y

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])

## Numpy 2D!

In [37]:
# lets make a list of lists
a = [[11,12,13], [21,22,23], [31,32,33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [38]:
# Now make an array
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [39]:
# how many dimensions?
A.ndim

2

In [40]:
# Shape?
A.shape

(3, 3)

In [42]:
#Comapre len and size in 2D
print(A.size) #number of elements
print(A.shape) 
A.size == len(A)

9
(3, 3)


False

### Acceder a los elementros del arreglo

In [43]:
#First you count the rows and then the columns. Always starting from 0!!
A[2,1]

32

In [44]:
# two ways to access the same element
A[2][0:2] == A[2,0:2]

array([ True,  True])

In [46]:
#When adding matrices, the rules for normal matrix addition are maintained.

A = np.array([ [1,2],[2,1] ])
B = np.array([ [3,4],[4,3] ])
Z=A+B
print('A:',A)
print('B:',B)
print('A+B:',Z)

A: [[1 2]
 [2 1]]
B: [[3 4]
 [4 3]]
A+B: [[4 6]
 [6 4]]


In [47]:
#Multiplying matrices multiplies each element and does not make a matrix product
Z = A*B
Z

array([[3, 8],
       [8, 3]])

In [48]:
#Dot product!
np.dot(A,B)

array([[11, 10],
       [10, 11]])

In [49]:
# Transposing matrix

np.linalg.inv(A)

array([[-0.33333333,  0.66666667],
       [ 0.66666667, -0.33333333]])